### PR TITLE
Docs fixes

### PR DESCRIPTION
**Pull request by gavvvr**
Hi @johanhaleby. I've read all the docs and found many outdated links, so I've decided to fix them. Feel free to adjust the PR if I did something wrong

### CODE REVIEW

**Comment by johanhaleby** [comment]
Wow! Huge thanks for this 🙏

**Comment by johanhaleby** [comment]
If you have any feedback or ideas for Occurrent, I'd love to hear them. You're not on the DDD CQRS/ES discord server by any chance?

**Comment by gavvvr** [comment]
@johanhaleby I am not, but I would be happy to join, because this is my are of interest. Could you please invite me?
I do not have any ideas for occurrent yet. I develop my 1st event sourcing application and so far I like occurrent's philosophy a lot. Can't imagine myself putting a business-logic to some framework-dependent classes with framework-specific annotations.

**Comment by johanhaleby** [comment]
@gavvvr You should go to this URL to join the discord server: https://discord.gg/sEZGSHNNbH

**Pull request merged**
